# Generated by Django 3.2 on 2022-05-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSolution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
