# Generated by Django 3.2 on 2022-05-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testSolution', '0002_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
