# Generated by Django 3.2 on 2022-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testSolution', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='language',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
